# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39009de8203c9da54642686244466562176252d4c0a161c14ecebd888b6b1587c9fb02323796b49de3015791af0d605eb28af943a9f0ef91f292f34daaf2d1f3

test:
  secret_key_base: f8605a14a45163de7fa97367fdc8f1e0cf517d4f110e32300bf28a6418748949bca343ae03c7c1d9f52aa64b5827dadc601044aa9147d009729b11a961ff3988

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
